// Code generated by go generate; DO NOT EDIT.
// This file contains pre-parsed default configuration to avoid runtime TOML parsing.

package config

// PreparsedDefaultConfig contains the compile-time parsed default configuration.
var PreparsedDefaultConfig = Config{
	CheckHostname: true,
	SetProxy:      true,
	CAInstall:     "auto",
	IPv6:          true,
	DNS: DNSConfig{
		Nameserver:   []string{"https://dnschina1.soraharu.com/dns-query", "https://77.88.8.8/dns-query", "https://dns.google/dns-query"},
		BootstrapDNS: []string{"tls://223.5.5.5"},
	},
	Timeout: TimeoutConfig{
		Dial: 30,
		DNS:  5,
	},
	Limit: LimitConfig{
		DNSCacheSize: 10000,
	},
	Log: LogConfig{
		Level: "INFO",
	},
	Server: ServerConfig{
		Address: "127.0.0.1",
		Port:    7654,
		PACHost: "127.0.0.1",
	},
	Preference: PreferenceConfig{
		Mode:          "standard",
		EnableTesting: true,
		TestTimeoutMs: 500,
		TestParallel:  true,
		MaxTestIPs:    10,
		CacheTTL:      300,
		CacheSize:     5000,
	},
	Update: UpdateConfig{
		AutoCheckUpdate:         true,
		AutoCheckRules:          true,
		AutoUpdate:              true,
		AutoUpdateRules:         true,
		CheckIntervalHours:      6,
		RulesCheckIntervalHours: 24,
		RulesURL:                "https://github.com/SpaceTimee/Cealing-Host/releases/latest/download/Cealing-Host.toml",
	},
	Security: SecurityConfig{
		MinChainLength: 2,
		CheckEKU:       true,
		CheckValidity:  true,
	},
}
