// Static built-in routing rules. Manually maintained; loaded verbatim by
// LoadRules() into the running binary. No runtime fetching or codegen.
//
// AlterHostname/Hosts are synced from Cealing-Host releases (currently
// 1.1.4.52) with these adaptations: browser-only (#) and disabled (^) rules
// skipped, $ prefixes stripped, IPv6-only hosts dropped (alter_hostname
// kept), empty hosts (127.0.0.1) skipped, and t.me/telegram.me kept as the
// precise "*.t.me"+"t.me" split instead of upstream's "*t.me" suffix form
// (which would hijack e.g. about.me). CertVerify/IgnoreExpiry are
// snirect-specific, validated against live front certificates.

package rules

var builtinRules = &Rules{
	AlterHostname: map[string]string{

		"*.buy.yahoo.com":          "buy.yahoo.com",
		"*.ggpht.com":              "g.cn",
		"*.ig.me":                  "",
		"*.media.tumblr.com":       "",
		"*.t.me":                   "",
		"*.w.wiki":                 "",
		"*.yahoo.com":              "www.yahoo.com",
		"*amazon.co.jp":            "amazon.com",
		"*android.com":             "g.cn",
		"*api.mega.co.nz":          "",
		"*apkmirror.com":           "",
		"*archive.org":             "",
		"*archiveofourown.org":     "",
		"*audiomack.com":           "",
		"*bbc.co.uk":               "",
		"*bbc.com":                 "",
		"*bbci.co.uk":              "",
		"*behance.net":             "behance.net",
		"*bilibili.tv":             "bilibili.tv",
		"*blogger.com":             "g.cn",
		"*character.ai":            "",
		"*claude.ai":               "claude.ai",
		"*dailymotion.com":         "",
		"*discord.com":             "",
		"*discord.gg":              "",
		"*discordapp.com":          "",
		"*discordapp.net":          "",
		"*disneyplus.com":          "disneyplus.com",
		"*dropbox.com":             "",
		"*duckduckgo.com":          "",
		"*e-hentai.org":            "",
		"*ehgt.org":                "",
		"*ehtracker.org":           "",
		"*ehwiki.org":              "",
		"*etsy.com":                "",
		"*exhentai.org":            "",
		"*eyny.com":                "",
		"*facebook.com":            "",
		"*fanbox.cc":               "pixivision.net",
		"*fbcdn.net":               "",
		"*flickr.com":              "",
		"*gamer.com.tw":            "",
		"*gelbooru.com":            "",
		"*github.com":              "",
		"*githubusercontent.com":   "",
		"*google.com":              "g.cn",
		"*google.com.hk":           "g.cn",
		"*gravatar.com":            "",
		"*greasyfork.org":          "",
		"*gstatic.com":             "g.cn",
		"*hentaiverse.org":         "",
		"*huggingface.co":          "huggingface.cn",
		"*imgur.com":               "",
		"*instagr.am":              "",
		"*instagram.com":           "",
		"*lumalabs.ai":             "vercel.com",
		"*mediawiki.org":           "",
		"*mega.io":                 "",
		"*mega.nz":                 "",
		"*netflix.com":             "netflix.com",
		"*nicovideo.jp":            "",
		"*nyaa.si":                 "ddos-guard.net",
		"*nyt.com":                 "",
		"*nytimes.com":             "",
		"*ok.ru":                   "",
		"*okx.com":                 "",
		"*onedrive.live.com":       "",
		"*patreon.com":             "",
		"*patreonusercontent.com":  "",
		"*pinimg.com":              "",
		"*pinterest.com":           "",
		"*pixeldrain.com":          "pixeldra.in",
		"*pixiv.net":               "pixivision.net",
		"*pornhub.com":             "",
		"*proton.me":               "",
		"*pximg.net":               "",
		"*quora.com":               "fs.quoracdn.net",
		"*redd.it":                 "",
		"*reddit.com":              "",
		"*redditmedia.com":         "",
		"*redditstatic.com":        "",
		"*rfi.fr":                  "",
		"*rumble.com":              "",
		"*rutube.ru":               "",
		"*scratch.mit.edu":         "",
		"*spotify.com":             "spotify.com",
		"*startpage.com":           "",
		"*steamcommunity.com":      "",
		"*sukebei.nyaa.si":         "",
		"*telegram.org":            "",
		"*telesco.pe":              "",
		"*tg.dev":                  "",
		"*thetvdb.com":             "",
		"*tumblr.com":              "",
		"*twitch.tv":               "",
		"*v2ex.com":                "",
		"*vercel.app":              "vercel.com",
		"*vimeo.com":               "",
		"*whatsapp.com":            "",
		"*whatsapp.net":            "",
		"*wikibooks.org":           "",
		"*wikidata.org":            "",
		"*wikifunctions.org":       "",
		"*wikimedia.org":           "",
		"*wikinews.org":            "",
		"*wikipedia.org":           "",
		"*wikiquote.org":           "",
		"*wikisource.org":          "",
		"*wikiversity.org":         "",
		"*wikivoyage.org":          "",
		"*wiktionary.org":          "",
		"*xhamster.com":            "zh.xhamster.com",
		"*xhamster42.desi":         "zh.xhamster42.desi",
		"*xnxx.com":                "",
		"*xvideos.com":             "",
		"*xvideos.red":             "",
		"*youtu.be":                "g.cn",
		"*youtube-nocookie.com":    "g.cn",
		"*youtube.com":             "g.cn",
		"*z-lib.help":              "",
		"*z-library.sk":            "",
		"a5.behance.net":           "a5.behance.net",
		"account-api.proton.me":    "",
		"account.nicovideo.jp":     "",
		"account.proton.me":        "",
		"api.audiomack.com":        "",
		"api.fanbox.cc":            "api.fanbox.cc",
		"api.github.com":           "",
		"ask.vrchat.com":           "",
		"assets.audiomack.com":     "",
		"assets.twitch.tv":         "",
		"auth.docker.io":           "",
		"blog.docker.io":           "",
		"business.whatsapp.com":    "",
		"calendar.proton.me":       "",
		"cdn-registry-1.docker.io": "",
		"cdn.jsdelivr.net":         "",
		"cdn1.cdn-telegram.org":    "",
		"cdn4.cdn-telegram.org":    "",
		"cdn5.cdn-telegram.org":    "",
		"codeload.github.com":      "",
		"community.github.com":     "",
		"consent.yahoo.com":        "consent.yahoo.com",

		"docker.io":                            "",
		"docs.docker.io":                       "",
		"docs-editor.proton.me":                "",
		"docs-rts.proton.me":                   "",
		"docs.github.com":                      "",
		"docs.proton.me":                       "",
		"drive.proton.me":                      "",
		"embed.nicovideo.jp":                   "",
		"external-content.duckduckgo.com":      "",
		"f-droid.org":                          "",
		"fdroid.org":                           "",
		"forum.f-droid.org":                    "",
		"fra-storage.proton.me":                "",
		"gemini.google.com":                    "",
		"get.docker.io":                        "",
		"gql.twitch.tv":                        "",
		"graphql.api.dailymotion.com":          "",
		"guce.yahoo.com":                       "guce.yahoo.com",
		"hello.vrchat.com":                     "",
		"hub.docker.com":                       "",
		"i.ytimg.com":                          "g.cn",
		"identity.flickr.com":                  "",
		"ig.me":                                "",
		"images.prismic.io":                    "imgix.net",
		"index.docker.io":                      "",
		"irc-ws.chat.twitch.tv":                "",
		"live.nicovideo.jp":                    "",
		"live2.nicovideo.jp":                   "",
		"lumo.proton.me":                       "",
		"m.twitch.tv":                          "",
		"mail.proton.me":                       "",
		"meet.proton.me":                       "",
		"music.audiomack.com":                  "",
		"notary.docker.io":                     "",
		"nvapi.nicovideo.jp":                   "",
		"objects-origin.githubusercontent.com": "",
		"ok.ru":                                "",
		"open.spotify.com":                     "",
		"panels.twitch.tv":                     "",
		"pass.proton.me":                       "",
		"passport.twitch.tv":                   "",
		"polymarket.com":                       "vercel.com",
		"production.cloudflare.docker.com":     "",
		"registry-1.docker.io":                 "",
		"registry.docker.io":                   "",
		"registry.hub.docker.com":              "",
		"resources.github.com":                 "",
		"s.yimg.com":                           "www.yahoo.com",
		"services.github.com":                  "",
		"sheets.proton.me":                     "",
		"sp.nicovideo.jp":                      "",
		"sso.proton.me":                        "",
		"status.docker.io":                     "",
		"store.steampowered.com":               "",
		"support.github.com":                   "",
		"t.me":                                 "",
		"telegram.me":                          "",
		"upld.e-hentai.org":                    "",
		"upload.wikimedia.org":                 "",
		"w.wiki":                               "",
		"wallet.proton.me":                     "",
		"wktk.nicovideo.jp":                    "",
		"www.docker.io":                        "",
		"www.ecosia.org":                       "www.ecosia.org",
		"www.f-droid.org":                      "",
		"www.ok.ru":                            "",
		"zrh-storage.proton.me":                "",
	},
	CertVerify: map[string]interface{}{
		"*.objects-origin.githubusercontent.com": []interface{}{"*.actions.githubusercontent.com", "actions.githubusercontent.com"},
		// Live leaf (SNI-stripped Proton hosts) presents *.proton.me / *.pr.tn —
		// the old protonmail.com allowlist rejected every proton.me subdomain.
		"*.proton.me":       []interface{}{"*.proton.me", "proton.me", "*.pr.tn", "pr.tn", "*.storage.proton.me", "*.pm.me", "*.protonmail.ch", "*.protonmail.com", "protonmail.com"},
		"*.redd.it":         []interface{}{"*.reddit.com", "reddit.com"},
		"*redd.it":          []interface{}{"*.reddit.com", "reddit.com"},
		"*.redditmedia.com": []interface{}{"*.reddit.com", "reddit.com"},
		"*redditmedia.com":  []interface{}{"*.reddit.com", "reddit.com"},
		"*redditstatic.com": []interface{}{"*.reddit.com", "reddit.com"},
		"*ggpht.com":        []interface{}{"*.google.cn", "google.cn"},
		"*google.com":       "g.cn",
		"*google.com.hk":    "g.cn",
		"*gstatic.com":      "g.cn",
		"*pixiv.net":        []interface{}{"*.pixivision.net", "pixivision.net"},
		"*youtube.com":      []interface{}{"*.google.cn", "google.cn"},
		"*ytimg.com":        []interface{}{"*.google.cn", "google.cn"},
		// android/blogger/youtu.be share the g.cn front with youtube — the old
		// healthdatanexus.ai allowlist is a dead front and rejects the real cert.
		"*android.com":   []interface{}{"*.google.cn", "google.cn", "g.cn", "*.g.cn"},
		"*audiomack.com": []interface{}{"*.cloudfront.net", "cloudfront.net"},
		"*bbc.co.uk":     []interface{}{"*.cdn.cyberarena.at", "cdn.cyberarena.at"},
		"*bbci.co.uk":    []interface{}{"*.cdn.cyberarena.at", "cdn.cyberarena.at"},
		// CDN hosts present their own *.cdn-telegram.org leaf (not *.telegram.org).
		"*cdn-telegram.org": []interface{}{"*.cdn-telegram.org", "cdn-telegram.org", "*.telegram.org", "telegram.org"},
		"*fanbox.cc":        []interface{}{"*.pixivision.net", "pixivision.net"},
		"*ig.me":            []interface{}{"*.instagram.com", "*.cdninstagram.com", "*.igsonar.com", "cdninstagram.com", "igsonar.com", "instagram.com"},
		"*instagr.am":       []interface{}{"*.instagram.com", "*.cdninstagram.com", "*.igsonar.com", "cdninstagram.com", "igsonar.com", "instagram.com"},
		"*mega.io":          []interface{}{"*.static.mega.co.nz", "static.mega.co.nz"},
		"*nicovideo.jp":     []interface{}{"*.cloudfront.net", "cloudfront.net"},
		"*ok.ru":            []interface{}{"*.ok.ru", "ok.ru"},
		"*t.me":             []interface{}{"*.telegram.org", "telegram.org"},
		// Live leaf at the Fastly IP is *.twitch.tv; assets.* still sits on
		// CloudFront — keep both so either front cert passes.
		"*twitch.tv":            []interface{}{"*.twitch.tv", "twitch.tv", "*.cloudfront.net", "cloudfront.net"},
		"*z-lib.help":           []interface{}{"*.go-to-library.sk", "go-to-library.sk"},
		"*z-library.sk":         []interface{}{"*.go-to-library.sk", "go-to-library.sk"},
		"ask.vrchat.com":        []interface{}{"*.discourse.org"},
		"hello.vrchat.com":      []interface{}{"*.squarespace.com", "squarespace.com"},
		"*blogger.com":          []interface{}{"*.google.cn", "google.cn", "g.cn", "*.g.cn"},
		"business.whatsapp.com": []interface{}{"*.facebook.com", "*.facebook.net", "*.fbcdn.net", "*.fbsbx.com", "*.m.facebook.com", "*.messenger.com", "*.xx.fbcdn.net", "*.xy.fbcdn.net", "*.xz.fbcdn.net", "facebook.com", "messenger.com"},
		"docs.github.com":       []interface{}{"*.githubassets.com", "githubassets.com"},
		"gemini.google.com":     false,
		"gemini.gstatic.com":    "g.cn",
		// identity.flickr.com is pinned (upstream rule) to a shared front whose
		// SNI-stripped default-tenant leaf is *.bridgify.com — observed live,
		// Amazon-issued. Without this allowlist the tunnel fails verification.
		"identity.flickr.com": []interface{}{"*.bridgify.com", "bridgify.com"},
		"ig.me":               []interface{}{"*.instagram.com", "*.cdninstagram.com", "*.igsonar.com", "cdninstagram.com", "igsonar.com", "instagram.com"},
		"instagr.am":          []interface{}{"*.instagram.com", "*.cdninstagram.com", "*.igsonar.com", "cdninstagram.com", "igsonar.com", "instagram.com"},
		"mega.io":             []interface{}{"*.static.mega.co.nz", "static.mega.co.nz"},
		"redditstatic.com":    []interface{}{"*.reddit.com", "reddit.com"},
		"*scratch.mit.edu":    []interface{}{"d.sni-645-default.ssl.fastly.net"},
		// api.fanbox.cc is pinned to its own Cloudflare IP (not the pixivision
		// front used by *fanbox.cc), so it presents a real *.fanbox.cc cert.
		"api.fanbox.cc":    []interface{}{"*.fanbox.cc", "fanbox.cc"},
		"*sukebei.nyaa.si": false,
		// These SNI-stripped fronts currently return empty-SAN / honeypot leaves
		// (CN=fallback.wgcz.net, please-go-away, bare IP). Disable verify so the
		// tunnel still opens; Hosts IPs may need a later refresh.
		"*okx.com":                    false,
		"*spotify.com":                false,
		"open.spotify.com":            false,
		"*xnxx.com":                   false,
		"*xvideos.com":                false,
		"*xvideos.red":                false,
		"graphql.api.dailymotion.com": false,
		"t.me":                        []interface{}{"*.telegram.org", "telegram.org"},
		"telegram.me":                 []interface{}{"*.telegram.org", "telegram.org"},
		"*telesco.pe":                 []interface{}{"*.telegram.org", "telegram.org"},
		"*tg.dev":                     []interface{}{"*.telegram.org", "telegram.org"},
		"www.google.com":              "g.cn",
		"www.gstatic.com":             "g.cn",
		"www.redditstatic.com":        []interface{}{"*.reddit.com", "reddit.com"},
		"*youtu.be":                   []interface{}{"*.google.cn", "google.cn", "g.cn", "*.g.cn"},
		"*youtube-nocookie.com":       []interface{}{"*.google.cn", "google.cn", "g.cn", "*.g.cn"},
	},
	Hosts: map[string]string{
		"*.ggpht.com":                     "183.56.143.147",
		"*.ig.me":                         "157.240.27.174",
		"*.media.tumblr.com":              "192.0.77.3",
		"*.t.me":                          "45.192.12.153",
		"*.w.wiki":                        "185.15.59.224",
		"*amazon.co.jp":                   "13.35.219.115",
		"*android.com":                    "183.56.143.147",
		"*api.mega.co.nz":                 "66.203.125.15",
		"*apkmirror.com":                  "104.17.67.215",
		"*archive.org":                    "207.241.237.2",
		"*archiveofourown.org":            "104.20.8.2",
		"*audiomack.com":                  "3.167.200.113",
		"*bbc.co.uk":                      "23.77.21.232",
		"*bbc.com":                        "146.75.36.81",
		"*bbci.co.uk":                     "23.77.21.232",
		"*blogger.com":                    "183.56.143.147",
		"*character.ai":                   "104.18.223.226",
		"*dailymotion.com":                "195.8.215.140",
		"*discord.com":                    "162.159.136.232",
		"*discord.gg":                     "162.159.130.234",
		"*discordapp.com":                 "162.159.130.233",
		"*discordapp.net":                 "162.159.130.232",
		"*dropbox.com":                    "162.125.248.18",
		"*duckduckgo.com":                 "20.43.161.105",
		"*e-hentai.org":                   "172.66.132.196",
		"*ehgt.org":                       "109.236.85.28",
		"*ehtracker.org":                  "5.79.104.115",
		"*ehwiki.org":                     "178.162.151.58",
		"*etsy.com":                       "151.101.193.224",
		"*exhentai.org":                   "178.175.132.22",
		"*eyny.com":                       "23.19.72.223",
		"*facebook.com":                   "157.240.22.169",
		"*fanbox.cc":                      "210.140.139.155",
		"*fbcdn.net":                      "157.240.22.169",
		"*flickr.com":                     "13.33.142.102",
		"*gamer.com.tw":                   "104.16.223.104",
		"*gelbooru.com":                   "108.181.143.72",
		"*github.com":                     "20.27.177.113",
		"*githubusercontent.com":          "185.199.108.133",
		"*google.com":                     "183.56.143.147",
		"*google.com.hk":                  "183.56.143.147",
		"*gravatar.com":                   "192.0.80.240",
		"*greasyfork.org":                 "96.126.98.220",
		"*gstatic.com":                    "183.56.143.147",
		"*hentaiverse.org":                "178.162.151.56",
		"*huggingface.co":                 "3.167.200.113",
		"*imgur.com":                      "199.232.196.193",
		"*instagr.am":                     "157.240.27.174",
		"*instagram.com":                  "157.240.27.174",
		"*lumalabs.ai":                    "76.76.21.21",
		"*mediawiki.org":                  "185.15.59.224",
		"*mega.io":                        "66.203.127.24",
		"*mega.nz":                        "31.216.144.5",
		"*nicovideo.jp":                   "3.167.200.113",
		"*nyaa.si":                        "186.2.163.20",
		"*nyt.com":                        "146.75.117.164",
		"*nytimes.com":                    "146.75.117.164",
		"*ok.ru":                          "5.61.23.30",
		"*okx.com":                        "8.212.101.92",
		"*onedrive.live.com":              "13.107.42.13",
		"*patreon.com":                    "104.16.25.14",
		"*patreonusercontent.com":         "104.18.70.106",
		"*pinimg.com":                     "151.101.0.84",
		"*pinterest.com":                  "151.101.0.84",
		"*pixeldrain.com":                 "103.107.198.191",
		"*pixiv.net":                      "210.140.139.155",
		"*pornhub.com":                    "66.254.114.40",
		"*proton.me":                      "185.70.42.45",
		"*pximg.net":                      "210.140.139.133",
		"*quora.com":                      "162.159.152.17",
		"*redd.it":                        "146.75.33.140",
		"*reddit.com":                     "146.75.33.140",
		"*redditmedia.com":                "146.75.33.140",
		"*redditstatic.com":               "146.75.33.140",
		"*rfi.fr":                         "118.214.247.61",
		"*rumble.com":                     "205.220.231.24",
		"*rutube.ru":                      "109.238.90.239",
		"*scratch.mit.edu":                "151.101.66.133",
		"*startpage.com":                  "67.63.60.231",
		"*steamcommunity.com":             "184.50.187.66",
		"*sukebei.nyaa.si":                "198.251.89.38",
		"*telegram.org":                   "45.192.12.153",
		"*telesco.pe":                     "45.192.12.153",
		"*tg.dev":                         "45.192.12.153",
		"*thetvdb.com":                    "13.35.222.88",
		"*tumblr.com":                     "192.0.77.40",
		"*twitch.tv":                      "151.101.194.167",
		"*v2ex.com":                       "172.66.137.6",
		"*vercel.app":                     "64.29.17.193",
		"*vimeo.com":                      "162.159.138.60",
		"*whatsapp.com":                   "157.240.225.60",
		"*whatsapp.net":                   "157.240.225.60",
		"*wikibooks.org":                  "185.15.59.224",
		"*wikidata.org":                   "185.15.59.224",
		"*wikifunctions.org":              "185.15.59.224",
		"*wikimedia.org":                  "185.15.59.224",
		"*wikinews.org":                   "185.15.59.224",
		"*wikipedia.org":                  "185.15.59.224",
		"*wikiquote.org":                  "185.15.59.224",
		"*wikisource.org":                 "185.15.59.224",
		"*wikiversity.org":                "185.15.59.224",
		"*wikivoyage.org":                 "185.15.59.224",
		"*wiktionary.org":                 "185.15.59.224",
		"*xhamster.com":                   "104.17.35.109",
		"*xhamster42.desi":                "104.17.35.109",
		"*xnxx.com":                       "89.222.127.8",
		"*xvideos.com":                    "89.222.127.8",
		"*xvideos.red":                    "89.222.127.8",
		"*youtu.be":                       "183.56.143.147",
		"*youtube-nocookie.com":           "183.56.143.147",
		"*youtube.com":                    "183.56.143.147",
		"*z-lib.help":                     "176.123.7.105",
		"*z-library.sk":                   "176.123.7.105",
		"a5.behance.net":                  "13.35.185.106",
		"account-api.proton.me":           "185.70.42.20",
		"account.nicovideo.jp":            "3.167.200.113",
		"account.proton.me":               "185.70.42.36",
		"api.audiomack.com":               "3.167.200.113",
		"api.fanbox.cc":                   "172.64.146.116",
		"api.github.com":                  "20.205.243.168",
		"ask.vrchat.com":                  "216.66.8.43",
		"assets.audiomack.com":            "3.167.200.113",
		"assets.twitch.tv":                "3.167.200.113",
		"auth.docker.io":                  "hub-origin.docker.com",
		"blog.docker.io":                  "elb-io.us-east-1.aws.dckr.io",
		"business.whatsapp.com":           "157.240.22.169",
		"calendar.proton.me":              "185.70.42.39",
		"cdn-registry-1.docker.io":        "registry.ipv4.docker.com",
		"cdn.jsdelivr.net":                "104.16.89.20",
		"cdn1.cdn-telegram.org":           "34.111.15.3",
		"cdn4.cdn-telegram.org":           "34.111.35.152",
		"cdn5.cdn-telegram.org":           "34.111.108.175",
		"codeload.github.com":             "20.205.243.165",
		"community.github.com":            "140.82.114.17",
		"consent.yahoo.com":               "consent.yahoo.com",
		"docker.io":                       "elb-io.us-east-1.aws.dckr.io",
		"docs.docker.io":                  "elb-io.us-east-1.aws.dckr.io",
		"docs-editor.proton.me":           "185.70.42.70",
		"docs-rts.proton.me":              "185.70.42.71",
		"docs.github.com":                 "185.199.110.154",
		"docs.proton.me":                  "185.70.42.69",
		"drive.proton.me":                 "185.70.42.40",
		"embed.nicovideo.jp":              "3.167.200.113",
		"external-content.duckduckgo.com": "20.43.160.189",
		"f-droid.org":                     "37.218.243.72",
		"fdroid.org":                      "37.218.243.72",
		"forum.f-droid.org":               "37.218.242.53",
		"fra-storage.proton.me":           "185.205.70.10",
		"gemini.google.com":               "47.102.115.14",
		"get.docker.io":                   "elb-io.us-east-1.aws.dckr.io",
		"gql.twitch.tv":                   "151.101.194.167",
		"graphql.api.dailymotion.com":     "34.84.14.157",
		"guce.yahoo.com":                  "guce.yahoo.com",
		"hello.vrchat.com":                "198.185.159.145",
		"hub.docker.com":                  "hub-origin.docker.com",
		"i.ytimg.com":                     "183.56.143.147",

		"identity.flickr.com": "100.57.141.104",
		"ig.me":               "157.240.27.174",
		"images.prismic.io":   "151.101.78.208",

		"index.docker.io":                      "registry.ipv4.docker.com",
		"irc-ws.chat.twitch.tv":                "3.167.200.113",
		"live.nicovideo.jp":                    "3.167.200.113",
		"live2.nicovideo.jp":                   "3.167.200.113",
		"lumo.proton.me":                       "185.70.42.51",
		"m.twitch.tv":                          "151.101.194.167",
		"mail.proton.me":                       "185.70.42.37",
		"meet.proton.me":                       "185.70.42.118",
		"music.audiomack.com":                  "3.167.200.113",
		"notary.docker.io":                     "elb-io.us-east-1.aws.dckr.io",
		"nvapi.nicovideo.jp":                   "3.167.200.113",
		"objects-origin.githubusercontent.com": "140.82.113.22",
		"ok.ru":                                "5.61.23.11",
		"panels.twitch.tv":                     "3.167.200.113",
		"pass.proton.me":                       "185.70.42.63",
		"passport.twitch.tv":                   "3.167.200.113",
		"polymarket.com":                       "64.239.109.1",
		"production.cloudflare.docker.com":     "104.16.100.215",
		"registry-1.docker.io":                 "registry.ipv4.docker.com",
		"registry.docker.io":                   "registry.ipv4.docker.com",
		"registry.hub.docker.com":              "elb-io.us-east-1.aws.dckr.io",
		"resources.github.com":                 "185.199.108.133",
		"services.github.com":                  "140.82.113.18",
		"sheets.proton.me":                     "185.70.42.69",
		"sp.nicovideo.jp":                      "3.167.200.113",
		"sso.proton.me":                        "185.70.42.20",
		"status.docker.io":                     "elb-io.us-east-1.aws.dckr.io",
		"store.steampowered.com":               "23.39.61.133",
		"support.github.com":                   "185.199.108.133",
		"t.me":                                 "45.192.12.153",
		"telegram.me":                          "45.192.12.153",
		"upld.e-hentai.org":                    "89.149.221.236",
		"upload.wikimedia.org":                 "208.80.154.240",
		"w.wiki":                               "185.15.59.224",
		"wallet.proton.me":                     "194.0.147.12",
		"wktk.nicovideo.jp":                    "3.167.200.113",
		"www.docker.io":                        "elb-io.us-east-1.aws.dckr.io",
		"www.f-droid.org":                      "37.218.243.72",
		"www.ok.ru":                            "5.61.23.11",
		"zrh-storage.proton.me":                "176.119.200.8",
	},
	// Front certs that are known to ship expired / short-lived LE leaves.
	// Without these, VerifyCert rejects the handshake even when the allowlist
	// would otherwise accept the domain names.
	IgnoreExpiry: map[string]bool{
		"*z-lib.help":           true,
		"*z-library.sk":         true,
		"*cdn-telegram.org":     true,
		"cdn1.cdn-telegram.org": true,
		"cdn4.cdn-telegram.org": true,
		"cdn5.cdn-telegram.org": true,
	},
	// Pre-sorted key indexes are NOT populated here. LoadRules() calls Init(),
	// which rebuilds them from the maps above via getSortedKeys — the maps are
	// the single source of truth. Hardcoding the slices here was a latent bug:
	// any map edit that wasn't mirrored into the slice became invisible to the
	// pattern-matching accessors (GetAlterHostname/GetCertVerify/GetHost).
}
