name: CI

on:
  push:
    branches: [ main, master ]
    tags-ignore:
      - "v*"
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-lint:
    name: Go Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2

      - name: Test
        run: make test

      - name: Build Cross CLI
        run: make crossAll
